### ISSUE TITLE
Setup Error: pod install 

### ISSUE THREAD

**Issue by erdicem** [Teknasyon-Teknoloji/desk360-livechat-ios-sdk#1]
- Dependency manager (Carthage, CocoaPods, SPM, Manually):

## What did you do?

> I added pod 'Desk360LiveChat' and info.plist requirements but ı face to face this problem and to solve tired!  "[!] Unable to find the Xcode project"

Do you have advise ?

**Comment by engali94** [comment]
Hi @Erdicem 
Can you please share a snippet of your Podfile if possible? it will help us understand your issue quickly
because it seems there is a problem in your Podfile structure/syntax

**Comment by erdicem** [comment]
hi @engali94 

<img width="380" alt="Screen Shot 2021-12-01 at 11 12 14" src="https://user-images.githubusercontent.com/58256667/144196374-f3aaadda-4060-4caa-bbc9-b934123913fe.png">

**Comment by engali94** [comment]
are you trying to build the Sample app attached with this repo? because seems this is an exact copy of the Example pod file

if this is the case you need to navigate to the desk360-live-chat folder:
run `xcodegen` to generate the Xcode Project
then run `pod install` to install the pods

**Comment by engali94** [comment]
a better way 
1. create your own project
2. init Pods
3. add `pod 'Desk360LiveChat'` to your Podfile
4. install
and you should be good to go.

**Comment by erdicem** [comment]
<img width="695" alt="Screen Shot 2021-12-01 at 12 03 31" src="https://user-images.githubusercontent.com/58256667/144204104-e6850b5f-7689-4878-a2cc-479f69fb9036.png">

<img width="766" alt="Screen Shot 2021-12-01 at 12 03 55" src="https://user-images.githubusercontent.com/58256667/144204154-b7b67680-3e7f-463d-8ae5-e29e90aefb7c.png">

@engali94  
I try solving but  I did not see LiveChat.xcodeproj  file. 

How I can solve this problem ?

**Comment by engali94** [comment]
please run `xcodegen` first

**Comment by erdicem** [comment]
Of course, but this project run Xcode 13 version ?

**Comment by engali94** [comment]
yeah there is no limitation of Xcode version
