### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code Error 

### ISSUE THREAD

**Issue by erdicem** [Teknasyon-Teknoloji/desk360-livechat-ios-sdk#3]
Hi team, 

I still try that build your example sdk, but I take this error 

<img width="472" alt="Screen Shot 2021-12-02 at 17 18 01" src="https://user-images.githubusercontent.com/58256667/144439395-a67eada9-68db-4456-93f3-0503e4cba3b4.png">

again and again. I solve xcodegen problem and I did pod install but not running project. I take this error. 

I did search and find these element, I did this advise but not solve this problem. 

<img width="1125" alt="Screen Shot 2021-12-02 at 17 21 01" src="https://user-images.githubusercontent.com/58256667/144439934-773bce11-84c4-4859-b07b-1ba1f2f60abd.png">

**Comment by engali94** [comment]
Hey @Erdicem 
You dont have Swiftlint installed on your machine. This is not related to the Chat SDK.
